from __future__ import annotations

from textwrap import dedent
from typing import Any, TypedDict

from libcst.codemod.visitors import ImportItem

from django_autotyping._compat import Required


class SettingTypingConfiguration(TypedDict, total=False):
    docs: str
    """The docstring of the setting."""

    type: Required[str]
    """The stringified type annotation to be used."""

    typing_imports: list[str]
    """A list of typing objects to be imported."""

    extra_imports: list[ImportItem]
    """A list of extra import items to be included."""

    extra_definitions: list[type[Any]]
    """A list of extra objects to be included in the file."""


# Type definitions specific to settings. They will be included in the type stubs
# assuming you included them in "extra_definitions". These objects do not exist at
# runtime, and so should be named with a leading underscore.


class _ChacheSetting(TypedDict, total=False):
    BACKEND: Required[str]
    """Default: ``''`` (Empty string)

    The cache backend to use. The built-in cache backends are:

    * ``'django.core.cache.backends.db.DatabaseCache'``
    * ``'django.core.cache.backends.dummy.DummyCache'``
    * ``'django.core.cache.backends.filebased.FileBasedCache'``
    * ``'django.core.cache.backends.locmem.LocMemCache'``
    * ``'django.core.cache.backends.memcached.PyMemcacheCache'``
    * ``'django.core.cache.backends.memcached.PyLibMCCache'``
    * ``'django.core.cache.backends.redis.RedisCache'``

    You can use a cache backend that doesn't ship with Django by setting
    :setting:`BACKEND <CACHES-BACKEND>` to a fully-qualified path of a cache
    backend class (i.e. ``mypackage.backends.whatever.WhateverCache``).
    """

    KEY_FUNCTION: str
    """A string containing a dotted path to a function (or any callable) that defines how to
    compose a prefix, version and key into a final cache key. The default
    implementation is equivalent to the function::

        def make_key(key, key_prefix, version):
            return ":".join([key_prefix, str(version), key])

    You may use any key function you want, as long as it has the same
    argument signature.

    See the :ref:`cache documentation <cache_key_transformation>` for more
    information.
    """

    KEY_PREFIX: str
    """Default: ``''`` (Empty string)

    A string that will be automatically included (prepended by default) to
    all cache keys used by the Django server.

    See the :ref:`cache documentation <cache_key_prefixing>` for more information.
    """

    LOCATION: str
    """Default: ``''`` (Empty string)

    The location of the cache to use. This might be the directory for a
    file system cache, a host and port for a memcache server, or an identifying
    name for a local memory cache. e.g.::

        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
                "LOCATION": "/var/tmp/django_cache",
            }
        }
    """

    OPTIONS: dict[str, Any] | None
    """Default: ``None``

    Extra parameters to pass to the cache backend. Available parameters
    vary depending on your cache backend.

    Some information on available parameters can be found in the
    :ref:`cache arguments <cache_arguments>` documentation. For more information,
    consult your backend module's own documentation.
    """

    TIMEOUT: int
    """Default: ``300``

    The number of seconds before a cache entry is considered stale. If the value of
    this setting is ``None``, cache entries will not expire. A value of ``0``
    causes keys to immediately expire (effectively "don't cache").
    """

    VERSION: int
    """Default: ``1``

    The default version number for cache keys generated by the Django server.

    See the :ref:`cache documentation <cache_versioning>` for more information.

    .. setting:: CACHE_MIDDLEWARE_ALIAS
    """


class _DatabaseTestSetting(TypedDict, total=False):
    CHARSET: str
    """Default: ``None``

    The character set encoding used to create the test database. The value of this
    string is passed directly through to the database, so its format is
    backend-specific.

    Supported by the PostgreSQL_ (``postgresql``) and MySQL_ (``mysql``) backends.

    .. _PostgreSQL: https://www.postgresql.org/docs/current/multibyte.html
    .. _MySQL: https://dev.mysql.com/doc/refman/en/charset-charsets.html
    """

    COLLATION: Any | None
    """Default: ``None``

    The collation order to use when creating the test database. This value is
    passed directly to the backend, so its format is backend-specific.

    Only supported for the ``mysql`` backend (see the `MySQL manual`_ for details).

    .. _MySQL manual: MySQL_
    """

    DEPENDENCIES: list[str]
    """Default: ``['default']``, for all databases other than ``default``,
    which has no dependencies.

    The creation-order dependencies of the database. See the documentation
    on :ref:`controlling the creation order of test databases
    <topics-testing-creation-dependencies>` for details.
    """

    MIGRATE: bool
    """Default: ``True``

    When set to ``False``, migrations won't run when creating the test database.
    This is similar to setting ``None`` as a value in :setting:`MIGRATION_MODULES`,
    but for all apps.
    """

    MIRROR: str | None
    """Default: ``None``

    The alias of the database that this database should mirror during
    testing. It depends on transactions and therefore must be used within
    :class:`~django.test.TransactionTestCase` instead of
    :class:`~django.test.TestCase`.

    This setting exists to allow for testing of primary/replica
    (referred to as master/slave by some databases)
    configurations of multiple databases. See the documentation on
    :ref:`testing primary/replica configurations
    <topics-testing-primaryreplica>` for details.
    """

    NAME: str | None
    """Default: ``None``

    The name of database to use when running the test suite.

    If the default value (``None``) is used with the SQLite database engine, the
    tests will use a memory resident database. For all other database engines the
    test database will use the name ``'test_' + DATABASE_NAME``.

    See :ref:`the-test-database`.
    """

    TEMPLATE: str
    """This is a PostgreSQL-specific setting.

    The name of a `template`_ (e.g. ``'template0'``) from which to create the test
    database.

    .. _template: https://www.postgresql.org/docs/current/sql-createdatabase.html
    """

    CREATE_DB: bool
    """Default: ``True``

    This is an Oracle-specific setting.

    If it is set to ``False``, the test tablespaces won't be automatically created
    at the beginning of the tests or dropped at the end.
    """

    CREATE_USER: bool
    """Default: ``True``

    This is an Oracle-specific setting.

    If it is set to ``False``, the test user won't be automatically created at the
    beginning of the tests and dropped at the end.
    """

    USER: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The username to use when connecting to the Oracle database that will be used
    when running tests. If not provided, Django will use ``'test_' + USER``.
    """

    PASSWORD: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The password to use when connecting to the Oracle database that will be used
    when running tests. If not provided, Django will generate a random password.
    """

    ORACLE_MANAGED_FILES: bool
    """Default: ``False``

    This is an Oracle-specific setting.

    If set to ``True``, Oracle Managed Files (OMF) tablespaces will be used.
    :setting:`DATAFILE` and :setting:`DATAFILE_TMP` will be ignored.
    """

    TBLSPACE: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The name of the tablespace that will be used when running tests. If not
    provided, Django will use ``'test_' + USER``.
    """

    TBLSPACE_TMP: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The name of the temporary tablespace that will be used when running tests. If
    not provided, Django will use ``'test_' + USER + '_temp'``.
    """

    DATAFILE: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The name of the datafile to use for the TBLSPACE. If not provided, Django will
    use ``TBLSPACE + '.dbf'``.
    """

    DATAFILE_TMP: str | None
    """Default: ``None``

    This is an Oracle-specific setting.

    The name of the datafile to use for the TBLSPACE_TMP. If not provided, Django
    will use ``TBLSPACE_TMP + '.dbf'``.
    """

    DATAFILE_MAXSIZE: str
    """Default: ``'500M'``

    This is an Oracle-specific setting.

    The maximum size that the DATAFILE is allowed to grow to.
    """

    DATAFILE_TMP_MAXSIZE: str
    """Default: ``'500M'``

    This is an Oracle-specific setting.

    The maximum size that the DATAFILE_TMP is allowed to grow to.
    """

    DATAFILE_SIZE: str
    """Default: ``'50M'``

    This is an Oracle-specific setting.

    The initial size of the DATAFILE.
    """

    DATAFILE_TMP_SIZE: str
    """Default: ``'50M'``

    This is an Oracle-specific setting.

    The initial size of the DATAFILE_TMP.
    """

    DATAFILE_EXTSIZE: str
    """Default: ``'25M'``

    This is an Oracle-specific setting.

    The amount by which the DATAFILE is extended when more space is required.
    """

    DATAFILE_TMP_EXTSIZE: str
    """Default: ``'25M'``

    This is an Oracle-specific setting.

    The amount by which the DATAFILE_TMP is extended when more space is required.
    """


class _DatabaseSetting(TypedDict, total=False):
    ATOMIC_REQUESTS: bool
    """Default: ``False``

    Set this to ``True`` to wrap each view in a transaction on this database. See
    :ref:`tying-transactions-to-http-requests`.
    """

    AUTOCOMMIT: bool
    """
    Default: ``True``

    Set this to ``False`` if you want to :ref:`disable Django's transaction
    management <deactivate-transaction-management>` and implement your own.
    """

    ENGINE: str
    """Default: ``''`` (Empty string)

    The database backend to use. The built-in database backends are:

    * ``'django.db.backends.postgresql'``
    * ``'django.db.backends.mysql'``
    * ``'django.db.backends.sqlite3'``
    * ``'django.db.backends.oracle'``

    You can use a database backend that doesn't ship with Django by setting
    ``ENGINE`` to a fully-qualified path (i.e. ``mypackage.backends.whatever``).
    """

    HOST: str
    """Default: ``''`` (Empty string)

    Which host to use when connecting to the database. An empty string means
    localhost. Not used with SQLite.

    If this value starts with a forward slash (``'/'``) and you're using MySQL,
    MySQL will connect via a Unix socket to the specified socket. For example::

        "HOST": "/var/run/mysql"

    If you're using MySQL and this value *doesn't* start with a forward slash, then
    this value is assumed to be the host.

    If you're using PostgreSQL, by default (empty :setting:`HOST`), the connection
    to the database is done through UNIX domain sockets ('local' lines in
    ``pg_hba.conf``). If your UNIX domain socket is not in the standard location,
    use the same value of ``unix_socket_directory`` from ``postgresql.conf``.
    If you want to connect through TCP sockets, set :setting:`HOST` to 'localhost'
    or '127.0.0.1' ('host' lines in ``pg_hba.conf``).
    On Windows, you should always define :setting:`HOST`, as UNIX domain sockets
    are not available.
    """

    NAME: str
    """Default: ``''`` (Empty string)

    The name of the database to use. For SQLite, it's the full path to the database
    file. When specifying the path, always use forward slashes, even on Windows
    (e.g. ``C:/homes/user/mysite/sqlite3.db``).
    """

    CONN_MAX_AGE: int
    """Default: ``0``

    The lifetime of a database connection, as an integer of seconds. Use ``0`` to
    close database connections at the end of each request — Django's historical
    behavior — and ``None`` for unlimited :ref:`persistent database connections
    <persistent-database-connections>`.
    """

    CONN_HEALTH_CHECKS: bool
    """Default: ``False``

    If set to ``True``, existing :ref:`persistent database connections
    <persistent-database-connections>` will be health checked before they are
    reused in each request performing database access. If the health check fails,
    the connection will be reestablished without failing the request when the
    connection is no longer usable but the database server is ready to accept and
    serve new connections (e.g. after database server restart closing existing
    connections).
    """

    OPTIONS: dict[str, Any]
    """Default: ``{}`` (Empty dictionary)

    Extra parameters to use when connecting to the database. Available parameters
    vary depending on your database backend.

    Some information on available parameters can be found in the
    :doc:`Database Backends </ref/databases>` documentation. For more information,
    consult your backend module's own documentation.
    """

    PASSWORD: str
    """Default: ``''`` (Empty string)

    The password to use when connecting to the database. Not used with SQLite.
    """

    PORT: str
    """Default: ``''`` (Empty string)

    The port to use when connecting to the database. An empty string means the
    default port. Not used with SQLite.
    """

    TIME_ZONE: str | None
    """Default: ``None``

    A string representing the time zone for this database connection or ``None``.
    This inner option of the :setting:`DATABASES` setting accepts the same values
    as the general :setting:`TIME_ZONE` setting.

    When :setting:`USE_TZ` is ``True``, reading datetimes from the database
    returns aware datetimes with the timezone set to this option's value if not
    ``None``, or to UTC otherwise.

    When :setting:`USE_TZ` is ``False``, it is an error to set this option.

    * If the database backend doesn't support time zones (e.g. SQLite, MySQL,
    Oracle), Django reads and writes datetimes in local time according to this
    option if it is set and in UTC if it isn't.

    Changing the connection time zone changes how datetimes are read from and
    written to the database.

    * If Django manages the database and you don't have a strong reason to do
        otherwise, you should leave this option unset. It's best to store datetimes
        in UTC because it avoids ambiguous or nonexistent datetimes during daylight
        saving time changes. Also, receiving datetimes in UTC keeps datetime
        arithmetic simple — there's no need to consider potential offset changes
        over a DST transition.

    * If you're connecting to a third-party database that stores datetimes in a
        local time rather than UTC, then you must set this option to the
        appropriate time zone. Likewise, if Django manages the database but
        third-party systems connect to the same database and expect to find
        datetimes in local time, then you must set this option.

    * If the database backend supports time zones (e.g., PostgreSQL), then the
    database connection's time zone is set to this value.

    Although setting the ``TIME_ZONE`` option is very rarely needed, there are
    situations where it becomes necessary. Specifically, it's recommended to
    match the general :setting:`TIME_ZONE` setting when dealing with raw queries
    involving date/time functions like PostgreSQL's ``date_trunc()`` or
    ``generate_series()``, especially when generating time-based series that
    transition daylight savings.

    This value can be changed at any time, the database will handle the
    conversion of datetimes to the configured time zone.

    However, this has a downside: receiving all datetimes in local time makes
    datetime arithmetic more tricky — you must account for possible offset
    changes over DST transitions.

    Consider converting to local time explicitly with ``AT TIME ZONE`` in raw SQL
    queries instead of setting the ``TIME_ZONE`` option.
    """

    DISABLE_SERVER_SIDE_CURSORS: bool
    """Default: ``False``

    Set this to ``True`` if you want to disable the use of server-side cursors with
    :meth:`.QuerySet.iterator`. :ref:`transaction-pooling-server-side-cursors`
    describes the use case.

    This is a PostgreSQL-specific setting.
    """

    USER: str
    """Default: ``''`` (Empty string)

    The username to use when connecting to the database. Not used with SQLite.
    """

    TEST: _DatabaseTestSetting
    """Default: ``{}`` (Empty dictionary)

    A dictionary of settings for test databases; for more details about the
    creation and use of test databases, see :ref:`the-test-database`.

    Here's an example with a test database configuration::

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "USER": "mydatabaseuser",
                "NAME": "mydatabase",
                "TEST": {
                    "NAME": "mytestdatabase",
                },
            },
        }
    """


GLOBAL_SETTINGS: dict[str, SettingTypingConfiguration] = {
    "ABSOLUTE_URL_OVERRIDES": {
        "docs": dedent(
            """
            Default: ``{}`` (Empty dictionary)

            A dictionary mapping ``"app_label.model_name"`` strings to functions that take
            a model object and return its URL. This is a way of inserting or overriding
            ``get_absolute_url()`` methods on a per-installation basis. Example::

                ABSOLUTE_URL_OVERRIDES = {
                    "blogs.blog": lambda o: "/blogs/%s/" % o.slug,
                    "news.story": lambda o: "/stories/%s/%s/" % (o.pub_year, o.slug),
                }

            The model name used in this setting should be all lowercase, regardless of the
            case of the actual model class name.
            """
        ),
        "type": "dict[str, Callable[[Model], str]]",
        "typing_imports": ["Callable"],
        "extra_imports": [ImportItem("django.db.models", "Model")],
    },
    "ADMINS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of all the people who get code error notifications. When
            :setting:`DEBUG=False <DEBUG>` and :class:`~django.utils.log.AdminEmailHandler`
            is configured in :setting:`LOGGING` (done by default), Django emails these
            people the details of exceptions raised in the request/response cycle.

            Each item in the list should be a tuple of (Full name, email address). Example::

                [("John", "john@example.com"), ("Mary", "mary@example.com")]
            """
        ),
        "type": "list[tuple[str, str]]",
    },
    "ALLOWED_HOSTS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of strings representing the host/domain names that this Django site can
            serve. This is a security measure to prevent :ref:`HTTP Host header attacks
            <host-headers-virtual-hosting>`, which are possible even under many
            seemingly-safe web server configurations.

            Values in this list can be fully qualified names (e.g. ``'www.example.com'``),
            in which case they will be matched against the request's ``Host`` header
            exactly (case-insensitive, not including port). A value beginning with a period
            can be used as a subdomain wildcard: ``'.example.com'`` will match
            ``example.com``, ``www.example.com``, and any other subdomain of
            ``example.com``. A value of ``'*'`` will match anything; in this case you are
            responsible to provide your own validation of the ``Host`` header (perhaps in a
            middleware; if so this middleware must be listed first in
            :setting:`MIDDLEWARE`).

            Django also allows the `fully qualified domain name (FQDN)`_ of any entries.
            Some browsers include a trailing dot in the ``Host`` header which Django
            strips when performing host validation.

            .. _`fully qualified domain name (FQDN)`: https://en.wikipedia.org/wiki/Fully_qualified_domain_name

            If the ``Host`` header (or ``X-Forwarded-Host`` if
            :setting:`USE_X_FORWARDED_HOST` is enabled) does not match any value in this
            list, the :meth:`django.http.HttpRequest.get_host()` method will raise
            :exc:`~django.core.exceptions.SuspiciousOperation`.

            When :setting:`DEBUG` is ``True`` and ``ALLOWED_HOSTS`` is empty, the host
            is validated against ``['.localhost', '127.0.0.1', '[::1]']``.

            ``ALLOWED_HOSTS`` is also :ref:`checked when running tests
            <topics-testing-advanced-multiple-hosts>`.

            This validation only applies via :meth:`~django.http.HttpRequest.get_host()`;
            if your code accesses the ``Host`` header directly from ``request.META`` you
            are bypassing this security protection.
            """
        ),
        "type": "list[str]",
    },
    "APPEND_SLASH": {
        "docs": dedent(
            """
            Default: ``True``

            When set to ``True``, if the request URL does not match any of the patterns
            in the URLconf and it doesn't end in a slash, an HTTP redirect is issued to the
            same URL with a slash appended. Note that the redirect may cause any data
            submitted in a POST request to be lost.

            The :setting:`APPEND_SLASH` setting is only used if
            :class:`~django.middleware.common.CommonMiddleware` is installed
            (see :doc:`/topics/http/middleware`). See also :setting:`PREPEND_WWW`.
            """
        ),
        "type": "bool",
    },
    "CACHES": {
        "docs": dedent(
            """
            Default::

                {
                    "default": {
                        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                    }
                }

            A dictionary containing the settings for all caches to be used with
            Django. It is a nested dictionary whose contents maps cache aliases
            to a dictionary containing the options for an individual cache.

            The :setting:`CACHES` setting must configure a ``default`` cache;
            any number of additional caches may also be specified. If you
            are using a cache backend other than the local memory cache, or
            you need to define multiple caches, other options will be required.
            The following cache options are available.
            """
        ),
        "type": "dict[str, _ChacheSetting]",
        "typing_imports": ["TypedDict", "Required"],
        "extra_definitions": [_ChacheSetting],
    },
    "CACHE_MIDDLEWARE_ALIAS": {
        "docs": dedent(
            """
            Default: ``'default'``

            The cache connection to use for the :ref:`cache middleware
            <the-per-site-cache>`.
            """
        ),
        "type": "str",
    },
    "CACHE_MIDDLEWARE_KEY_PREFIX": {
        "docs": dedent(
            """
            Default: ``''`` (Empty string)

            A string which will be prefixed to the cache keys generated by the :ref:`cache
            middleware <the-per-site-cache>`. This prefix is combined with the
            :setting:`KEY_PREFIX <CACHES-KEY_PREFIX>` setting; it does not replace it.

            See :doc:`/topics/cache`.
            """
        ),
        "type": "str",
    },
    "CACHE_MIDDLEWARE_SECONDS": {
        "docs": dedent(
            """
            Default: ``600``

            The default number of seconds to cache a page for the :ref:`cache middleware
            <the-per-site-cache>`.

            See :doc:`/topics/cache`.
            """
        ),
        "type": "int",
    },
    "CSRF_COOKIE_AGE": {
        "docs": dedent(
            """
            Default: ``31449600`` (approximately 1 year, in seconds)

            The age of CSRF cookies, in seconds.

            The reason for setting a long-lived expiration time is to avoid problems in
            the case of a user closing a browser or bookmarking a page and then loading
            that page from a browser cache. Without persistent cookies, the form submission
            would fail in this case.

            Some browsers (specifically Internet Explorer) can disallow the use of
            persistent cookies or can have the indexes to the cookie jar corrupted on disk,
            thereby causing CSRF protection checks to (sometimes intermittently) fail.
            Change this setting to ``None`` to use session-based CSRF cookies, which
            keep the cookies in-memory instead of on persistent storage.
            """
        ),
        "type": "int",
    },
    "CSRF_COOKIE_DOMAIN": {
        "docs": dedent(
            """
            Default: ``None``

            The domain to be used when setting the CSRF cookie.  This can be useful for
            easily allowing cross-subdomain requests to be excluded from the normal cross
            site request forgery protection.  It should be set to a string such as
            ``".example.com"`` to allow a POST request from a form on one subdomain to be
            accepted by a view served from another subdomain.

            Please note that the presence of this setting does not imply that Django's CSRF
            protection is safe from cross-subdomain attacks by default - please see the
            :ref:`CSRF limitations <csrf-limitations>` section.
            """
        ),
        "type": "str | None",
    },
    "CSRF_COOKIE_HTTPONLY": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use ``HttpOnly`` flag on the CSRF cookie. If this is set to
            ``True``, client-side JavaScript will not be able to access the CSRF cookie.

            Designating the CSRF cookie as ``HttpOnly`` doesn't offer any practical
            protection because CSRF is only to protect against cross-domain attacks. If an
            attacker can read the cookie via JavaScript, they're already on the same domain
            as far as the browser knows, so they can do anything they like anyway. (XSS is
            a much bigger hole than CSRF.)

            Although the setting offers little practical benefit, it's sometimes required
            by security auditors.

            If you enable this and need to send the value of the CSRF token with an AJAX
            request, your JavaScript must pull the value :ref:`from a hidden CSRF token
            form input <acquiring-csrf-token-from-html>` instead of :ref:`from the cookie
            <acquiring-csrf-token-from-cookie>`.

            See :setting:`SESSION_COOKIE_HTTPONLY` for details on ``HttpOnly``.
            """
        ),
        "type": "bool",
    },
    "CSRF_COOKIE_NAME": {
        "docs": dedent(
            """
            Default: ``'csrftoken'``

            The name of the cookie to use for the CSRF authentication token. This can be
            whatever you want (as long as it's different from the other cookie names in
            your application). See :doc:`/ref/csrf`.
            """
        ),
        "type": "str",
    },
    "CSRF_COOKIE_PATH": {
        "docs": dedent(
            """
            Default: ``'/'``

            The path set on the CSRF cookie. This should either match the URL path of your
            Django installation or be a parent of that path.

            This is useful if you have multiple Django instances running under the same
            hostname. They can use different cookie paths, and each instance will only see
            its own CSRF cookie.
            """
        ),
        "type": "str",
    },
    "CSRF_COOKIE_SAMESITE": {
        "docs": dedent(
            """
            Default: ``'Lax'``

            The value of the `SameSite`_ flag on the CSRF cookie. This flag prevents the
            cookie from being sent in cross-site requests.

            See :setting:`SESSION_COOKIE_SAMESITE` for details about ``SameSite``.
            """
        ),
        "type": 'Literal["Strict", "Lax", "None", False]',
        "typing_imports": ["Literal"],
    },
    "CSRF_COOKIE_SECURE": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use a secure cookie for the CSRF cookie. If this is set to ``True``,
            the cookie will be marked as "secure", which means browsers may ensure that the
            cookie is only sent with an HTTPS connection.
            """
        ),
        "type": "bool",
    },
    "CSRF_USE_SESSIONS": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to store the CSRF token in the user's session instead of in a cookie.
            It requires the use of :mod:`django.contrib.sessions`.

            Storing the CSRF token in a cookie (Django's default) is safe, but storing it
            in the session is common practice in other web frameworks and therefore
            sometimes demanded by security auditors.

            Since the :ref:`default error views <error-views>` require the CSRF token,
            :class:`~django.contrib.sessions.middleware.SessionMiddleware` must appear in
            :setting:`MIDDLEWARE` before any middleware that may raise an exception to
            trigger an error view (such as :exc:`~django.core.exceptions.PermissionDenied`)
            if you're using ``CSRF_USE_SESSIONS``. See :ref:`middleware-ordering`.
            """
        ),
        "type": "bool",
    },
    "CSRF_FAILURE_VIEW": {
        "docs": dedent(
            """
            Default: ``'django.views.csrf.csrf_failure'``

            A dotted path to the view function to be used when an incoming request is
            rejected by the :doc:`CSRF protection </ref/csrf>`. The function should have
            this signature::

                def csrf_failure(request, reason=""):
                    ...

            where ``reason`` is a short message (intended for developers or logging, not
            for end users) indicating the reason the request was rejected. It should return
            an :class:`~django.http.HttpResponseForbidden`.

            ``django.views.csrf.csrf_failure()`` accepts an additional ``template_name``
            parameter that defaults to ``'403_csrf.html'``. If a template with that name
            exists, it will be used to render the page.
            """
        ),
        "type": "str",
    },
    "CSRF_HEADER_NAME": {
        "docs": dedent(
            """
            Default: ``'HTTP_X_CSRFTOKEN'``

            The name of the request header used for CSRF authentication.

            As with other HTTP headers in ``request.META``, the header name received from
            the server is normalized by converting all characters to uppercase, replacing
            any hyphens with underscores, and adding an ``'HTTP_'`` prefix to the name.
            For example, if your client sends a ``'X-XSRF-TOKEN'`` header, the setting
            should be ``'HTTP_X_XSRF_TOKEN'``.
            """
        ),
        "type": "str",
    },
    "CSRF_TRUSTED_ORIGINS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of trusted origins for unsafe requests (e.g. ``POST``).

            For requests that include the ``Origin`` header, Django's CSRF protection
            requires that header match the origin present in the ``Host`` header.

            For a :meth:`secure <django.http.HttpRequest.is_secure>` unsafe
            request that doesn't include the ``Origin`` header, the request must have a
            ``Referer`` header that matches the origin present in the ``Host`` header.

            These checks prevent, for example, a ``POST`` request from
            ``subdomain.example.com`` from succeeding against ``api.example.com``. If you
            need cross-origin unsafe requests, continuing the example, add
            ``'https://subdomain.example.com'`` to this list (and/or ``http://...`` if
            requests originate from an insecure page).

            The setting also supports subdomains, so you could add
            ``'https://*.example.com'``, for example, to allow access from all subdomains
            of ``example.com``.
            """
        ),
        "type": "list[str]",
    },
    "DATABASES": {
        "docs": dedent(
            """
            Default: ``{}`` (Empty dictionary)

            A dictionary containing the settings for all databases to be used with
            Django. It is a nested dictionary whose contents map a database alias
            to a dictionary containing the options for an individual database.

            The :setting:`DATABASES` setting must configure a ``default`` database;
            any number of additional databases may also be specified.

            The simplest possible settings file is for a single-database setup using
            SQLite. This can be configured using the following::

                DATABASES = {
                    "default": {
                        "ENGINE": "django.db.backends.sqlite3",
                        "NAME": "mydatabase",
                    }
                }

            When connecting to other database backends, such as MariaDB, MySQL, Oracle, or
            PostgreSQL, additional connection parameters will be required. See
            the :setting:`ENGINE <DATABASE-ENGINE>` setting below on how to specify
            other database types. This example is for PostgreSQL::

                DATABASES = {
                    "default": {
                        "ENGINE": "django.db.backends.postgresql",
                        "NAME": "mydatabase",
                        "USER": "mydatabaseuser",
                        "PASSWORD": "mypassword",
                        "HOST": "127.0.0.1",
                        "PORT": "5432",
                    }
                }
            """
        ),
        "type": "dict[str, _DatabaseSetting]",
        "extra_definitions": [_DatabaseSetting, _DatabaseTestSetting],
    },
    "DATA_UPLOAD_MAX_MEMORY_SIZE": {
        "docs": dedent(
            """
            Default: ``2621440`` (i.e. 2.5 MB).

            The maximum size in bytes that a request body may be before a
            :exc:`~django.core.exceptions.SuspiciousOperation` (``RequestDataTooBig``) is
            raised. The check is done when accessing ``request.body`` or ``request.POST``
            and is calculated against the total request size excluding any file upload
            data. You can set this to ``None`` to disable the check. Applications that are
            expected to receive unusually large form posts should tune this setting.

            The amount of request data is correlated to the amount of memory needed to
            process the request and populate the GET and POST dictionaries. Large requests
            could be used as a denial-of-service attack vector if left unchecked. Since web
            servers don't typically perform deep request inspection, it's not possible to
            perform a similar check at that level.

            See also :setting:`FILE_UPLOAD_MAX_MEMORY_SIZE`.
            """
        ),
        "type": "int",
    },
    "DATA_UPLOAD_MAX_NUMBER_FIELDS": {
        "docs": dedent(
            """
            Default: ``1000``

            The maximum number of parameters that may be received via GET or POST before a
            :exc:`~django.core.exceptions.SuspiciousOperation` (``TooManyFields``) is
            raised. You can set this to ``None`` to disable the check. Applications that
            are expected to receive an unusually large number of form fields should tune
            this setting.

            The number of request parameters is correlated to the amount of time needed to
            process the request and populate the GET and POST dictionaries. Large requests
            could be used as a denial-of-service attack vector if left unchecked. Since web
            servers don't typically perform deep request inspection, it's not possible to
            perform a similar check at that level.
            """
        ),
        "type": "int",
    },
    "DATA_UPLOAD_MAX_NUMBER_FILES": {
        "docs": dedent(
            """
            Default: ``100``

            The maximum number of files that may be received via POST in a
            ``multipart/form-data`` encoded request before a
            :exc:`~django.core.exceptions.SuspiciousOperation` (``TooManyFiles``) is
            raised. You can set this to ``None`` to disable the check. Applications that
            are expected to receive an unusually large number of file fields should tune
            this setting.

            The number of accepted files is correlated to the amount of time and memory
            needed to process the request. Large requests could be used as a
            denial-of-service attack vector if left unchecked. Since web servers don't
            typically perform deep request inspection, it's not possible to perform a
            similar check at that level.
            """
        ),
        "type": "int",
    },
    "DATABASE_ROUTERS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            The list of routers that will be used to determine which database
            to use when performing a database query.

            See the documentation on :ref:`automatic database routing in multi
            database configurations <topics-db-multi-db-routing>`.
            """
        ),
        "type": "list[str]",
    },
    "DATE_FORMAT": {
        "docs": dedent(
            """
            Default: ``'N j, Y'`` (e.g. ``Feb. 4, 2003``)

            The default formatting to use for displaying date fields in any part of the
            system. Note that the locale-dictated format has higher precedence and will be
            applied instead. See :tfilter:`allowed date format strings <date>`.

            See also :setting:`DATETIME_FORMAT`, :setting:`TIME_FORMAT` and :setting:`SHORT_DATE_FORMAT`.
            """
        ),
        "type": "str",
    },
    "DATE_INPUT_FORMATS": {
        "docs": dedent(
            """
            Default::

                [
                    "%Y-%m-%d",  # '2006-10-25'
                    "%m/%d/%Y",  # '10/25/2006'
                    "%m/%d/%y",  # '10/25/06'
                    "%b %d %Y",  # 'Oct 25 2006'
                    "%b %d, %Y",  # 'Oct 25, 2006'
                    "%d %b %Y",  # '25 Oct 2006'
                    "%d %b, %Y",  # '25 Oct, 2006'
                    "%B %d %Y",  # 'October 25 2006'
                    "%B %d, %Y",  # 'October 25, 2006'
                    "%d %B %Y",  # '25 October 2006'
                    "%d %B, %Y",  # '25 October, 2006'
                ]

            A list of formats that will be accepted when inputting data on a date field.
            Formats will be tried in order, using the first valid one. Note that these
            format strings use Python's :ref:`datetime module syntax
            <strftime-strptime-behavior>`, not the format strings from the :tfilter:`date`
            template filter.

            The locale-dictated format has higher precedence and will be applied instead.

            See also :setting:`DATETIME_INPUT_FORMATS` and :setting:`TIME_INPUT_FORMATS`.
            """
        ),
        "type": "list[str]",
    },
    "DATETIME_FORMAT": {
        "docs": dedent(
            """
            Default: ``'N j, Y, P'`` (e.g. ``Feb. 4, 2003, 4 p.m.``)

            The default formatting to use for displaying datetime fields in any part of the
            system. Note that the locale-dictated format has higher precedence and will be
            applied instead. See :tfilter:`allowed date format strings <date>`.

            See also :setting:`DATE_FORMAT`, :setting:`TIME_FORMAT` and :setting:`SHORT_DATETIME_FORMAT`.
            """
        ),
        "type": "str",
    },
    "DATETIME_INPUT_FORMATS": {
        "docs": dedent(
            """
            Default::

                [
                    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
                    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
                    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
                    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
                    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
                    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
                    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
                    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
                    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
                ]

            A list of formats that will be accepted when inputting data on a datetime
            field. Formats will be tried in order, using the first valid one. Note that
            these format strings use Python's :ref:`datetime module syntax
            <strftime-strptime-behavior>`, not the format strings from the :tfilter:`date`
            template filter. Date-only formats are not included as datetime fields will
            automatically try :setting:`DATE_INPUT_FORMATS` in last resort.

            The locale-dictated format has higher precedence and will be applied instead.

            See also :setting:`DATE_INPUT_FORMATS` and :setting:`TIME_INPUT_FORMATS`.
            """
        ),
        "type": "list[str]",
    },
    "DEBUG": {
        "docs": dedent(
            """
            Default: ``False``

            A boolean that turns on/off debug mode.

            Never deploy a site into production with :setting:`DEBUG` turned on.

            One of the main features of debug mode is the display of detailed error pages.
            If your app raises an exception when :setting:`DEBUG` is ``True``, Django will
            display a detailed traceback, including a lot of metadata about your
            environment, such as all the currently defined Django settings (from
            ``settings.py``).

            As a security measure, Django will *not* include settings that might be
            sensitive, such as :setting:`SECRET_KEY`. Specifically, it will exclude any
            setting whose name includes any of the following:

            * ``'API'``
            * ``'KEY'``
            * ``'PASS'``
            * ``'SECRET'``
            * ``'SIGNATURE'``
            * ``'TOKEN'``

            Note that these are *partial* matches. ``'PASS'`` will also match PASSWORD,
            just as ``'TOKEN'`` will also match TOKENIZED and so on.

            Still, note that there are always going to be sections of your debug output
            that are inappropriate for public consumption. File paths, configuration
            options and the like all give attackers extra information about your server.

            It is also important to remember that when running with :setting:`DEBUG`
            turned on, Django will remember every SQL query it executes. This is useful
            when you're debugging, but it'll rapidly consume memory on a production server.

            Finally, if :setting:`DEBUG` is ``False``, you also need to properly set
            the :setting:`ALLOWED_HOSTS` setting. Failing to do so will result in all
            requests being returned as "Bad Request (400)".

            .. note::

                The default :file:`settings.py` file created by :djadmin:`django-admin
                startproject <startproject>` sets ``DEBUG = True`` for convenience.
            """
        ),
        "type": "bool",
    },
    "DEBUG_PROPAGATE_EXCEPTIONS": {
        "docs": dedent(
            """
            Default: ``False``

            If set to ``True``, Django's exception handling of view functions
            (:data:`~django.conf.urls.handler500`, or the debug view if :setting:`DEBUG`
            is ``True``) and logging of 500 responses (:ref:`django-request-logger`) is
            skipped and exceptions propagate upward.

            This can be useful for some test setups. It shouldn't be used on a live site
            unless you want your web server (instead of Django) to generate "Internal
            Server Error" responses. In that case, make sure your server doesn't show the
            stack trace or other sensitive information in the response.
            """
        ),
        "type": "bool",
    },
    "DECIMAL_SEPARATOR": {
        "docs": dedent(
            """
            Default: ``'.'`` (Dot)

            Default decimal separator used when formatting decimal numbers.

            Note that the locale-dictated format has higher precedence and will be applied
            instead.

            See also :setting:`NUMBER_GROUPING`, :setting:`THOUSAND_SEPARATOR` and
            :setting:`USE_THOUSAND_SEPARATOR`.
            """
        ),
        "type": "str",
    },
    "DEFAULT_AUTO_FIELD": {
        "docs": dedent(
            """
            Default: ``'``:class:`django.db.models.AutoField` ``'``

            Default primary key field type to use for models that don't have a field with
            :attr:`primary_key=True <django.db.models.Field.primary_key>`.

            .. admonition:: Migrating auto-created through tables

                The value of ``DEFAULT_AUTO_FIELD`` will be respected when creating new
                auto-created through tables for many-to-many relationships.

                Unfortunately, the primary keys of existing auto-created through tables
                cannot currently be updated by the migrations framework.

                This means that if you switch the value of ``DEFAULT_AUTO_FIELD`` and then
                generate migrations, the primary keys of the related models will be
                updated, as will the foreign keys from the through table, but the primary
                key of the auto-created through table will not be migrated.

                In order to address this, you should add a
                :class:`~django.db.migrations.operations.RunSQL` operation to your
                migrations to perform the required ``ALTER TABLE`` step. You can check the
                existing table name through ``sqlmigrate``, ``dbshell``, or with the
                field's ``remote_field.through._meta.db_table`` property.

                Explicitly defined through models are already handled by the migrations
                system.

                Allowing automatic migrations for the primary key of existing auto-created
                through tables :ticket:`may be implemented at a later date <32674>`.
            """
        ),
        "type": "str",
    },
    "DEFAULT_CHARSET": {
        "docs": dedent(
            """
            Default: ``'utf-8'``

            Default charset to use for all ``HttpResponse`` objects, if a MIME type isn't
            manually specified. Used when constructing the ``Content-Type`` header.
            """
        ),
        "type": "str",
    },
    "DEFAULT_EXCEPTION_REPORTER": {
        "docs": dedent(
            """
            Default: ``'``:class:`django.views.debug.SafeExceptionReporterFilter` ``'``

            Default exception reporter filter class to be used if none has been assigned to
            the :class:`~django.http.HttpRequest` instance yet.
            See :ref:`Filtering error reports<filtering-error-reports>`.
            """
        ),
        "type": "str",
    },
    "DEFAULT_FROM_EMAIL": {
        "docs": dedent(
            """
            Default: ``'webmaster@localhost'``

            Default email address for automated correspondence from the site manager(s).
            This address is used in the ``From:`` header of outgoing emails and can take
            any format valid in the chosen email sending protocol.

            This doesn't affect error messages sent to :setting:`ADMINS` and
            :setting:`MANAGERS`. See :setting:`SERVER_EMAIL` for that.
            """
        ),
        "type": "str",
    },
    "DEFAULT_INDEX_TABLESPACE": {
        "docs": dedent(
            """
            Default: ``''`` (Empty string)

            Default tablespace to use for indexes on fields that don't specify
            one, if the backend supports it (see :doc:`/topics/db/tablespaces`).
            """
        ),
        "type": "str",
    },
    "DEFAULT_TABLESPACE": {
        "docs": dedent(
            """
            Default: ``''`` (Empty string)

            Default tablespace to use for models that don't specify one, if the
            backend supports it (see :doc:`/topics/db/tablespaces`).
            """
        ),
        "type": "str",
    },
    "DISALLOWED_USER_AGENTS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            List of compiled regular expression objects representing User-Agent strings
            that are not allowed to visit any page, systemwide. Use this for bots/crawlers.
            This is only used if ``CommonMiddleware`` is installed (see
            :doc:`/topics/http/middleware`).
            """
        ),
        "type": "list[str]",
    },
    "EMAIL_BACKEND": {
        "docs": dedent(
            """
            Default: ``'``:class:`django.core.mail.backends.smtp.EmailBackend` ``'``

            The backend to use for sending emails. For the list of available backends see
            :ref:`topic-email-backends`.
            """
        ),
        "type": "str",
    },
    "EMAIL_FILE_PATH": {
        "docs": dedent(
            """
            Default: Not defined

            The directory used by the :ref:`file email backend <topic-email-file-backend>`
            to store output files.
            """
        ),
        "type": "Any",  # TODO what type?
    },
    "EMAIL_HOST": {
        "docs": dedent(
            """
            Default: ``'localhost'``

            The host to use for sending email.

            See also :setting:`EMAIL_PORT`.
            """
        ),
        "type": "str",
    },
    "EMAIL_HOST_PASSWORD": {
        "docs": dedent(
            """
            Default: ``''`` (Empty string)

            Password to use for the SMTP server defined in :setting:`EMAIL_HOST`. This
            setting is used in conjunction with :setting:`EMAIL_HOST_USER` when
            authenticating to the SMTP server. If either of these settings is empty,
            Django won't attempt authentication.

            See also :setting:`EMAIL_HOST_USER`.
            """
        ),
        "type": "str",
    },
    "EMAIL_HOST_USER": {
        "docs": dedent(
            """
            Default: ``''`` (Empty string)

            Username to use for the SMTP server defined in :setting:`EMAIL_HOST`.
            If empty, Django won't attempt authentication.

            See also :setting:`EMAIL_HOST_PASSWORD`.
            """
        ),
        "type": "str",
    },
    "EMAIL_PORT": {
        "docs": dedent(
            """
            Default: ``25``

            Port to use for the SMTP server defined in :setting:`EMAIL_HOST`.
            """
        ),
        "type": "25",
    },
    "EMAIL_SUBJECT_PREFIX": {
        "docs": dedent(
            """
            Default: ``'[Django] '``

            Subject-line prefix for email messages sent with ``django.core.mail.mail_admins``
            or ``django.core.mail.mail_managers``. You'll probably want to include the
            trailing space.
            """
        ),
        "type": "str",
    },
    "EMAIL_USE_LOCALTIME": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to send the SMTP ``Date`` header of email messages in the local time
            zone (``True``) or in UTC (``False``).
            """
        ),
        "type": "bool",
    },
    "EMAIL_USE_TLS": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use a TLS (secure) connection when talking to the SMTP server.
            This is used for explicit TLS connections, generally on port 587. If you are
            experiencing hanging connections, see the implicit TLS setting
            :setting:`EMAIL_USE_SSL`.
            """
        ),
        "type": "bool",
    },
    "EMAIL_USE_SSL": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use an implicit TLS (secure) connection when talking to the SMTP
            server. In most email documentation this type of TLS connection is referred
            to as SSL. It is generally used on port 465. If you are experiencing problems,
            see the explicit TLS setting :setting:`EMAIL_USE_TLS`.

            Note that :setting:`EMAIL_USE_TLS`/:setting:`EMAIL_USE_SSL` are mutually
            exclusive, so only set one of those settings to ``True``.
            """
        ),
        "type": "bool",
    },
    "EMAIL_SSL_CERTFILE": {
        "docs": dedent(
            """
            Default: ``None``

            If :setting:`EMAIL_USE_SSL` or :setting:`EMAIL_USE_TLS` is ``True``, you can
            optionally specify the path to a PEM-formatted certificate chain file to use
            for the SSL connection.
            """
        ),
        "type": "StrOrBytesPath | None",
        "extra_imports": [ImportItem("_typeshed", "StrOrBytesPath")],
    },
    "EMAIL_SSL_KEYFILE": {
        "docs": dedent(
            """
            Default: ``None``

            If :setting:`EMAIL_USE_SSL` or :setting:`EMAIL_USE_TLS` is ``True``, you can
            optionally specify the path to a PEM-formatted private key file to use for the
            SSL connection.

            Note that setting :setting:`EMAIL_SSL_CERTFILE` and :setting:`EMAIL_SSL_KEYFILE`
            doesn't result in any certificate checking. They're passed to the underlying SSL
            connection. Please refer to the documentation of Python's
            :meth:`python:ssl.SSLContext.wrap_socket` function for details on how the
            certificate chain file and private key file are handled.
            """
        ),
        "type": "StrOrBytesPath | None",
        "extra_imports": [ImportItem("_typeshed", "StrOrBytesPath")],
    },
    "EMAIL_TIMEOUT": {
        "docs": dedent(
            """
            Default: ``None``

            Specifies a timeout in seconds for blocking operations like the connection
            attempt.
            """
        ),
        "type": "int | None",
    },
    "FILE_UPLOAD_HANDLERS": {
        "docs": dedent(
            """
            Default::

                [
                    "django.core.files.uploadhandler.MemoryFileUploadHandler",
                    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
                ]

            A list of handlers to use for uploading. Changing this setting allows complete
            customization -- even replacement -- of Django's upload process.

            See :doc:`/topics/files` for details.
            """
        ),
        "type": "list[str]",
    },
    "FILE_UPLOAD_MAX_MEMORY_SIZE": {
        "docs": dedent(
            """
            Default: ``2621440`` (i.e. 2.5 MB).

            The maximum size (in bytes) that an upload will be before it gets streamed to
            the file system. See :doc:`/topics/files` for details.

            See also :setting:`DATA_UPLOAD_MAX_MEMORY_SIZE`.
            """
        ),
        "type": "int",
    },
    "FILE_UPLOAD_DIRECTORY_PERMISSIONS": {
        "docs": dedent(
            """
            Default: ``None``

            The numeric mode to apply to directories created in the process of uploading
            files.

            This setting also determines the default permissions for collected static
            directories when using the :djadmin:`collectstatic` management command. See
            :djadmin:`collectstatic` for details on overriding it.

            This value mirrors the functionality and caveats of the
            :setting:`FILE_UPLOAD_PERMISSIONS` setting.
            """
        ),
        "type": "int | None",
    },
    "FILE_UPLOAD_PERMISSIONS": {
        "docs": dedent(
            """
            Default: ``0o644``

            The numeric mode (i.e. ``0o644``) to set newly uploaded files to. For
            more information about what these modes mean, see the documentation for
            :func:`os.chmod`.

            If ``None``, you'll get operating-system dependent behavior. On most platforms,
            temporary files will have a mode of ``0o600``, and files saved from memory will
            be saved using the system's standard umask.

            For security reasons, these permissions aren't applied to the temporary files
            that are stored in :setting:`FILE_UPLOAD_TEMP_DIR`.

            This setting also determines the default permissions for collected static files
            when using the :djadmin:`collectstatic` management command. See
            :djadmin:`collectstatic` for details on overriding it.

            .. warning::

                **Always prefix the mode with** ``0o`` **.**

                If you're not familiar with file modes, please note that the ``0o`` prefix
                is very important: it indicates an octal number, which is the way that
                modes must be specified. If you try to use ``644``, you'll get totally
                incorrect behavior.
            """
        ),
        "type": "int",
    },
    "FILE_UPLOAD_TEMP_DIR": {
        "docs": dedent(
            """
            Default: ``None``

            The directory to store data to (typically files larger than
            :setting:`FILE_UPLOAD_MAX_MEMORY_SIZE`) temporarily while uploading files.
            If ``None``, Django will use the standard temporary directory for the operating
            system. For example, this will default to ``/tmp`` on *nix-style operating
            systems.

            See :doc:`/topics/files` for details.
            """
        ),
        "type": "GenericPath[AnyStr] | None",
        "extra_imports": [ImportItem("_typeshed", "GenericPath")],
        "typing_imports": ["AnyStr"],
    },
    "FIRST_DAY_OF_WEEK": {
        "docs": dedent(
            """
            Default: ``0`` (Sunday)

            A number representing the first day of the week. This is especially useful
            when displaying a calendar. This value is only used when not using
            format internationalization, or when a format cannot be found for the
            current locale.

            The value must be an integer from 0 to 6, where 0 means Sunday, 1 means
            Monday and so on.
            """
        ),
        "type": "int",
    },
    "FIXTURE_DIRS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            List of directories searched for :ref:`fixture <fixtures-explanation>` files,
            in addition to the ``fixtures`` directory of each application, in search order.

            Note that these paths should use Unix-style forward slashes, even on Windows.

            See :ref:`initial-data-via-fixtures` and :ref:`topics-testing-fixtures`.
            """
        ),
        "type": "list[PathLike[AnyStr]]",
        "extra_imports": [ImportItem("os", "PathLike")],
        "typing_imports": ["AnyStr"],
    },
    "FORCE_SCRIPT_NAME": {
        "docs": dedent(
            """
            Default: ``None``

            If not ``None``, this will be used as the value of the ``SCRIPT_NAME``
            environment variable in any HTTP request. This setting can be used to override
            the server-provided value of ``SCRIPT_NAME``, which may be a rewritten version
            of the preferred value or not supplied at all. It is also used by
            :func:`django.setup()` to set the URL resolver script prefix outside of the
            request/response cycle (e.g. in management commands and standalone scripts) to
            generate correct URLs when ``SCRIPT_NAME`` is not ``/``.
            """
        ),
        "type": "str | None",
    },
    "FORM_RENDERER": {
        "docs": dedent(
            """
            Default: ``'``:class:`django.forms.renderers.DjangoTemplates` ``'``

            The class that renders forms and form widgets. It must implement
            :ref:`the low-level render API <low-level-widget-render-api>`. Included form
            renderers are:

            * ``'``:class:`django.forms.renderers.DjangoTemplates` ``'``
            * ``'``:class:`django.forms.renderers.Jinja2` ``'``
            * ``'``:class:`django.forms.renderers.TemplatesSetting` ``'``
            """
        ),
        "type": "str",
    },
    "FORMS_URLFIELD_ASSUME_HTTPS": {
        "docs": dedent(
            """
            .. versionadded:: 5.0
            .. deprecated:: 5.0

            Default: ``False``

            Set this transitional setting to ``True`` to opt into using ``"https"`` as the
            new default value of :attr:`URLField.assume_scheme
            <django.forms.URLField.assume_scheme>` during the Django 5.x release cycle.
            """
        ),
        "type": "bool",
    },
    "FORMAT_MODULE_PATH": {
        "docs": dedent(
            """
            Default: ``None``

            A full Python path to a Python package that contains custom format definitions
            for project locales. If not ``None``, Django will check for a ``formats.py``
            file, under the directory named as the current locale, and will use the
            formats defined in this file.

            For example, if :setting:`FORMAT_MODULE_PATH` is set to ``mysite.formats``,
            and current language is ``en`` (English), Django will expect a directory tree
            like:

            .. code-block:: text

                mysite/
                    formats/
                        __init__.py
                        en/
                            __init__.py
                            formats.py

            You can also set this setting to a list of Python paths, for example::

                FORMAT_MODULE_PATH = [
                    "mysite.formats",
                    "some_app.formats",
                ]

            When Django searches for a certain format, it will go through all given Python
            paths until it finds a module that actually defines the given format. This
            means that formats defined in packages farther up in the list will take
            precedence over the same formats in packages farther down.

            Available formats are:

            * :setting:`DATE_FORMAT`
            * :setting:`DATE_INPUT_FORMATS`
            * :setting:`DATETIME_FORMAT`,
            * :setting:`DATETIME_INPUT_FORMATS`
            * :setting:`DECIMAL_SEPARATOR`
            * :setting:`FIRST_DAY_OF_WEEK`
            * :setting:`MONTH_DAY_FORMAT`
            * :setting:`NUMBER_GROUPING`
            * :setting:`SHORT_DATE_FORMAT`
            * :setting:`SHORT_DATETIME_FORMAT`
            * :setting:`THOUSAND_SEPARATOR`
            * :setting:`TIME_FORMAT`
            * :setting:`TIME_INPUT_FORMATS`
            * :setting:`YEAR_MONTH_FORMAT`
            """
        ),
        "type": "list[str]",
    },
    "IGNORABLE_404_URLS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            List of compiled regular expression objects describing URLs that should be
            ignored when reporting HTTP 404 errors via email (see
            :doc:`/howto/error-reporting`). Regular expressions are matched against
            :meth:`request's full paths <django.http.HttpRequest.get_full_path>` (including
            query string, if any). Use this if your site does not provide a commonly
            requested file such as ``favicon.ico`` or ``robots.txt``.

            This is only used if
            :class:`~django.middleware.common.BrokenLinkEmailsMiddleware` is enabled (see
            :doc:`/topics/http/middleware`).
            """
        ),
        "type": "list[Pattern[str]]",
        "extra_imports": [ImportItem("re", "Pattern")],
    },
    "INSTALLED_APPS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of strings designating all applications that are enabled in this
            Django installation. Each string should be a dotted Python path to:

            * an application configuration class (preferred), or
            * a package containing an application.

            :doc:`Learn more about application configurations </ref/applications>`.

            .. admonition:: Use the application registry for introspection

                Your code should never access :setting:`INSTALLED_APPS` directly. Use
                :attr:`django.apps.apps` instead.

            .. admonition:: Application names and labels must be unique in
                            :setting:`INSTALLED_APPS`

                Application :attr:`names <django.apps.AppConfig.name>` — the dotted Python
                path to the application package — must be unique. There is no way to
                include the same application twice, short of duplicating its code under
                another name.

                Application :attr:`labels <django.apps.AppConfig.label>` — by default the
                final part of the name — must be unique too. For example, you can't
                include both ``django.contrib.auth`` and ``myproject.auth``. However, you
                can relabel an application with a custom configuration that defines a
                different :attr:`~django.apps.AppConfig.label`.

                These rules apply regardless of whether :setting:`INSTALLED_APPS`
                references application configuration classes or application packages.

            When several applications provide different versions of the same resource
            (template, static file, management command, translation), the application
            listed first in :setting:`INSTALLED_APPS` has precedence.
            """
        ),
        "type": "list[str]",
    },
    "INTERNAL_IPS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of IP addresses, as strings, that:

            * Allow the :func:`~django.template.context_processors.debug` context processor
            to add some variables to the template context.
            * Can use the :ref:`admindocs bookmarklets <admindocs-bookmarklets>` even if
            not logged in as a staff user.
            * Are marked as "internal" (as opposed to "EXTERNAL") in
            :class:`~django.utils.log.AdminEmailHandler` emails.
            """
        ),
        "type": "list[str]",
    },
    "LANGUAGE_CODE": {
        "docs": dedent(
            """
            Default: ``'en-us'``

            A string representing the language code for this installation. This should be in
            standard :term:`language ID format <language code>`. For example, U.S. English
            is ``"en-us"``. See also the `list of language identifiers`_ and
            :doc:`/topics/i18n/index`.

            :setting:`USE_I18N` must be active for this setting to have any effect.

            It serves two purposes:

            * If the locale middleware isn't in use, it decides which translation is served
            to all users.
            * If the locale middleware is active, it provides a fallback language in case the
            user's preferred language can't be determined or is not supported by the
            website. It also provides the fallback translation when a translation for a
            given literal doesn't exist for the user's preferred language.

            See :ref:`how-django-discovers-language-preference` for more details.

            .. _list of language identifiers: http://www.i18nguy.com/unicode/language-identifiers.html
            """
        ),
        "type": "str",
    },
    "LANGUAGE_COOKIE_AGE": {
        "docs": dedent(
            """
            Default: ``None`` (expires at browser close)

            The age of the language cookie, in seconds.
            """
        ),
        "type": "str | None",
    },
    "LANGUAGE_COOKIE_DOMAIN": {
        "docs": dedent(
            """
            Default: ``None``

            The domain to use for the language cookie. Set this to a string such as
            ``"example.com"`` for cross-domain cookies, or use ``None`` for a standard
            domain cookie.

            Be cautious when updating this setting on a production site. If you update
            this setting to enable cross-domain cookies on a site that previously used
            standard domain cookies, existing user cookies that have the old domain
            will not be updated. This will result in site users being unable to switch
            the language as long as these cookies persist. The only safe and reliable
            option to perform the switch is to change the language cookie name
            permanently (via the :setting:`LANGUAGE_COOKIE_NAME` setting) and to add
            a middleware that copies the value from the old cookie to a new one and then
            deletes the old one.
            """
        ),
        "type": "str | None",
    },
    "LANGUAGE_COOKIE_HTTPONLY": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use ``HttpOnly`` flag on the language cookie. If this is set to
            ``True``, client-side JavaScript will not be able to access the language
            cookie.

            See :setting:`SESSION_COOKIE_HTTPONLY` for details on ``HttpOnly``.
            """
        ),
        "type": "bool",
    },
    "LANGUAGE_COOKIE_NAME": {
        "docs": dedent(
            """
            Default: ``'django_language'``

            The name of the cookie to use for the language cookie. This can be whatever
            you want (as long as it's different from the other cookie names in your
            application). See :doc:`/topics/i18n/index`.
            """
        ),
        "type": "str",
    },
    "LANGUAGE_COOKIE_PATH": {
        "docs": dedent(
            """
            Default: ``'/'``

            The path set on the language cookie. This should either match the URL path of your
            Django installation or be a parent of that path.

            This is useful if you have multiple Django instances running under the same
            hostname. They can use different cookie paths and each instance will only see
            its own language cookie.

            Be cautious when updating this setting on a production site. If you update this
            setting to use a deeper path than it previously used, existing user cookies that
            have the old path will not be updated. This will result in site users being
            unable to switch the language as long as these cookies persist. The only safe
            and reliable option to perform the switch is to change the language cookie name
            permanently (via the :setting:`LANGUAGE_COOKIE_NAME` setting), and to add
            a middleware that copies the value from the old cookie to a new one and then
            deletes the one.
            """
        ),
        "type": "str",
    },
    "LANGUAGE_COOKIE_SAMESITE": {
        "docs": dedent(
            """
            Default: ``None``

            The value of the `SameSite`_ flag on the language cookie. This flag prevents the
            cookie from being sent in cross-site requests.

            See :setting:`SESSION_COOKIE_SAMESITE` for details about ``SameSite``.
            """
        ),
        "type": 'Literal["Strict", "Lax", "None", False, None]',  # TODO "None" vs `None`?
    },
    "LANGUAGE_COOKIE_SECURE": {
        "docs": dedent(
            """
            Default: ``False``

            Whether to use a secure cookie for the language cookie. If this is set to
            ``True``, the cookie will be marked as "secure", which means browsers may
            ensure that the cookie is only sent under an HTTPS connection.
            """
        ),
        "type": "bool",
    },
    "LANGUAGES": {
        "docs": dedent(
            """
            Default: A list of all available languages. This list is continually growing
            and including a copy here would inevitably become rapidly out of date. You can
            see the current list of translated languages by looking in
            :source:`django/conf/global_settings.py`.

            The list is a list of 2-tuples in the format
            (:term:`language code<language code>`, ``language name``) -- for example,
            ``('ja', 'Japanese')``.
            This specifies which languages are available for language selection. See
            :doc:`/topics/i18n/index`.

            Generally, the default value should suffice. Only set this setting if you want
            to restrict language selection to a subset of the Django-provided languages.

            If you define a custom :setting:`LANGUAGES` setting, you can mark the
            language names as translation strings using the
            :func:`~django.utils.translation.gettext_lazy` function.

            Here's a sample settings file::

                from django.utils.translation import gettext_lazy as _

                LANGUAGES = [
                    ("de", _("German")),
                    ("en", _("English")),
                ]
            """
        ),
        "type": "list[tuple[str, str | _StrPromise]]",
        "extra_imports": [ImportItem("django.utils.functional", "_StrPromise")],
    },
    "LANGUAGES_BIDI": {
        "docs": dedent(
            """
            Default: A list of all language codes that are written right-to-left. You can
            see the current list of these languages by looking in
            :source:`django/conf/global_settings.py`.

            The list contains :term:`language codes<language code>` for languages that are
            written right-to-left.

            Generally, the default value should suffice. Only set this setting if you want
            to restrict language selection to a subset of the Django-provided languages.
            If you define a custom :setting:`LANGUAGES` setting, the list of bidirectional
            languages may contain language codes which are not enabled on a given site.
            """
        ),
        "type": "list[str]",
    },
    "LOCALE_PATHS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list of directories where Django looks for translation files.
            See :ref:`how-django-discovers-translations`.

            Example::

                LOCALE_PATHS = [
                    "/home/www/project/common_files/locale",
                    "/var/local/translations/locale",
                ]

            Django will look within each of these paths for the ``<locale_code>/LC_MESSAGES``
            directories containing the actual translation files.
            """
        ),
        "type": "list[str]",  # TODO or PathLike, but should check where `all_locale_paths` is used before
    },
    "LOGGING": {
        "docs": dedent(
            """
            Default: A logging configuration dictionary.

            A data structure containing configuration information. When not-empty, the
            contents of this data structure will be passed as the argument to the
            configuration method described in :setting:`LOGGING_CONFIG`.

            Among other things, the default logging configuration passes HTTP 500 server
            errors to an email log handler when :setting:`DEBUG` is ``False``. See also
            :ref:`configuring-logging`.

            You can see the default logging configuration by looking in
            :source:`django/utils/log.py`.
            """
        ),
        "type": "_DictConfigArgs",  # TODO what if `LOGGING_CONFIG` points to a different function?
        "extra_imports": [ImportItem("logging.config", "_DictConfigArgs")],
    },
    "LOGGING_CONFIG": {
        "docs": dedent(
            """
            Default: ``'logging.config.dictConfig'``

            A path to a callable that will be used to configure logging in the
            Django project. Points at an instance of Python's :ref:`dictConfig
            <logging-config-dictschema>` configuration method by default.

            If you set :setting:`LOGGING_CONFIG` to ``None``, the logging
            configuration process will be skipped.
            """
        ),
        "type": "str | None",
    },
    "MANAGERS": {
        "docs": dedent(
            """
            Default: ``[]`` (Empty list)

            A list in the same format as :setting:`ADMINS` that specifies who should get
            broken link notifications when
            :class:`~django.middleware.common.BrokenLinkEmailsMiddleware` is enabled.
            """
        ),
        "type": "list[tuple[str, str]]",
    },
}
