site_name: "Django Autotyping"
site_description: "Automatically add type hints for Django powered applications."
repo_url: https://github.com/Viicos/django-autotyping
repo_name: Viicos/django-autotyping
edit_uri: edit/main/docs/
watch: [mkdocs.yml, src/django_autotyping, docs]

theme:
  name: material
  features:
    - content.action.view
    - content.code.copy
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    view: material/eye
    repo: fontawesome/brands/github

nav:
  - Home:
    - Index: index.md
    - Context: context.md
    - Usage:
      - 'Dynamic stubs': usage/dynamic_stubs.md
      - 'Explicit type hints': usage/explicit_type_hints.md
    - API:
      - 'Dynamic stubs':
        - Rules: api/dynamic_stubs/rules.md
      - 'Explicit type hints':
        - Rules: api/explicit_type_hints/rules.md
      - Typing: api/typing.md
    - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - search
  - autorefs
  - mkdocstrings:
      # TODO remove when https://github.com/mkdocstrings/python/pull/130 eventually gets merged:
      custom_templates: _templates
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3.13/objects.inv
            - url: https://docs.djangoproject.com/en/dev/_objects
              domains: [std,py]
            - url: https://typing.readthedocs.io/en/latest/objects.inv
              domains: [std]
            - url: https://mypy.readthedocs.io/en/stable/objects.inv
              domains: [std]
            - url: https://peps.python.org/objects.inv
              domains: [std]
